---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/programs":
    get:
      summary: list programs
      responses:
        '200':
          description: successful
    post:
      summary: create program
      responses:
        '200':
          description: successful
  "/api/v1/programs/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show program
      responses:
        '200':
          description: successful
    patch:
      summary: update program
      responses:
        '200':
          description: successful
    put:
      summary: update program
      responses:
        '200':
          description: successful
    delete:
      summary: delete program
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: rsmine.fvds.ru
securityDefinitions:
  Bearer:
    description: "..."
    type: apiKey
    name: Authorization
    in: header
